/lmppi_node:
  ros__parameters:
    accel_scale: 4.0
    control_sample_std_accel: 2.0
    control_sample_std_steer: 0.5
    damping: 0.001
    friction: 0.16
    init_vel: 1.2
    is_sim: false
    latacc_cost_enabled: false
    latacc_cost_safe: 80.0
    latacc_cost_weight: 3.0
    map_dir: ./waypoints/
    map_ind: 0
    marker_frame_id: map
    max_speed: 2.0
    max_steering_angle: 0.4189
    min_speed: 0.0
    n_iterations: 1
    n_samples: 1024
    n_steps: 12
    optimal_line_width: 0.08
    publish_markers: true
    random_seed: 527787
    ref_vel: 2.0
    reference_line_width: 0.06
    render: true
    sampled_line_width: 0.025
    sampled_trajectory_alpha: 0.18
    sampled_trajectory_count: 32
    sim_time_step: 0.1
    slip_cost_beta_safe: 0.4
    slip_cost_enabled: false
    slip_cost_weight: 2.0
    speed_profile_drive_blend: 0.0
    speed_profile_drive_lookahead_steps: 2
    speed_profile_drive_max_accel: 1.0
    speed_profile_drive_max_decel: 3.0
    speed_profile_drive_use_min_lookahead: true
    speed_profile_iterations: 3
    speed_profile_lookahead_steps: 4
    speed_profile_max_speed: 4.1
    speed_profile_min_speed: 1.3
    speed_profile_scale: 1.0
    startup_speed: 1.0
    state_predictor: dynamic_ST
    steer_sat_cost_enabled: false
    steer_sat_cost_weight: 0.5
    steer_sat_soft_ratio: 0.85
    steer_vel_scale: 3.0
    temperature: 0.05
    use_pose_delta_state_estimate: true
    use_sim_time: false
    use_speed_profile_drive_speed: true
    use_waypoint_speed_profile: true
    velocity_reward_weight: 0.05
    wall_cost_enabled: false
    wall_cost_map_yaml: /home/nvidia/f1tenth_ws/install/mppi_bringup/share/mppi_bringup/maps/ice_rink1.yaml
    wall_cost_margin: 0.2
    wall_cost_power: 2.0
    wall_cost_weight: 100.0
    wpt_path: /home/nvidia/f1tenth_ws/install/mppi_bringup/share/mppi_bringup/waypoints/lev_testing/racetrack_lev1.csv
    wpt_path_absolute: true
    xy_reward_weight: 0.25
    yaw_reward_weight: 0.01

